/** Builds the committed, dependency-complete JavaScript Action and checks it for drift in CI. */

import { build } from 'esbuild';
import { cp, mkdtemp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename, dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const committed = join(root, 'action');
const check = process.argv.includes('--check');

async function filesBelow(directory, current = directory) {
  const found = [];
  for (const entry of (await readdir(current, { withFileTypes: true }))
    .sort((left, right) => left.name.localeCompare(right.name, 'en'))) {
    const path = join(current, entry.name);
    if (entry.isDirectory()) found.push(...await filesBelow(directory, path));
    else found.push(relative(directory, path).replaceAll('\\', '/'));
  }
  return found;
}

function packageNames(metafile) {
  const names = new Set();
  for (const input of Object.keys(metafile.inputs)) {
    const path = input.replaceAll('\\', '/');
    const marker = 'node_modules/';
    const index = path.lastIndexOf(marker);
    if (index < 0) continue;
    const parts = path.slice(index + marker.length).split('/');
    names.add(parts[0].startsWith('@') ? `${parts[0]}/${parts[1]}` : parts[0]);
  }
  return [...names].sort((left, right) => left.localeCompare(right, 'en'));
}

async function thirdPartyNotices(metafile) {
  const sections = ['Third-party software bundled in the Scrollcase GitHub Action', ''];
  for (const name of packageNames(metafile)) {
    const directory = join(root, 'node_modules', ...name.split('/'));
    const metadata = JSON.parse(await readFile(join(directory, 'package.json'), 'utf8'));
    const licenseName = (await readdir(directory))
      .filter((entry) => /^licen[cs]e(?:\.|$)/i.test(entry))
      .sort((left, right) => left.localeCompare(right, 'en'))[0];
    if (!licenseName) throw new Error(`Bundled package ${name} has no license file.`);
    const license = (await readFile(join(directory, licenseName), 'utf8')).replaceAll('\r\n', '\n').trim();
    sections.push(`${name} ${metadata.version} (${metadata.license ?? 'license in included text'})`, '', license, '');
  }
  return sections.join('\n');
}

async function generate(destination) {
  const output = join(destination, 'dist', 'index.cjs');
  await mkdir(dirname(output), { recursive: true });
  const result = await build({
    entryPoints: [join(root, 'action', 'src', 'main.mjs')],
    outfile: output,
    bundle: true,
    platform: 'node',
    target: 'node24',
    format: 'cjs',
    define: { 'import.meta.url': '__scrollcaseImportMetaUrl' },
    legalComments: 'none',
    metafile: true,
    banner: { js: [
      '// Generated by npm run action:build. Edit action/src/ or src/, then rebuild.',
      "const __scrollcaseImportMetaUrl = require('node:url').pathToFileURL(__filename).href;",
    ].join('\n') },
  });
  await writeFile(join(destination, 'dist', 'THIRD_PARTY_NOTICES.txt'), await thirdPartyNotices(result.metafile));
  await cp(join(root, 'src', 'contract', 'schema'), join(destination, 'contract', 'schema'), { recursive: true });
}

async function compare(expectedRoot) {
  const generatedFiles = (await filesBelow(expectedRoot)).sort();
  const committedFiles = [
    ...await filesBelow(join(committed, 'dist')).then((items) => items.map((item) => `dist/${item}`)),
    ...await filesBelow(join(committed, 'contract')).then((items) => items.map((item) => `contract/${item}`)),
  ].sort();
  if (JSON.stringify(generatedFiles) !== JSON.stringify(committedFiles)) {
    throw new Error('Action generated file list has drifted. Run npm run action:build.');
  }
  for (const file of generatedFiles) {
    const expected = await readFile(join(expectedRoot, file));
    const actual = await readFile(join(committed, file));
    if (!expected.equals(actual)) throw new Error(`Action bundle drift: ${file}. Run npm run action:build.`);
  }
}

const staging = await mkdtemp(join(tmpdir(), 'scrollcase-action-'));
try {
  await generate(staging);
  if (check) {
    await compare(staging);
  } else {
    await rm(join(committed, 'dist'), { recursive: true, force: true });
    await rm(join(committed, 'contract'), { recursive: true, force: true });
    await cp(join(staging, 'dist'), join(committed, 'dist'), { recursive: true });
    await cp(join(staging, 'contract'), join(committed, 'contract'), { recursive: true });
  }
} finally {
  await rm(staging, { recursive: true, force: true });
}
